spring:
  data:
    mongodb:
      uri: mongodb+srv://happesingh27:Cq3bieKL9HVIBj3G@cluster0.ahyvsmf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: happesingh27@gmail.com
    password: zfpl mtps ahtq nkvs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp


server:
  port: 8080
  #servlet:
    #context-path:/journal

logging:
  level:
    org:
      springframework:
        security: DEBUG # logging levels can be set here, and it can be customized to any level,
        # we can change logging leve, turn off logs for any particular class, package or for all classes, packages
        # research and study more about it and update these notes
        # same can be done using .properties or xml file
        # we would use separate xml file for logs, for cleaner folder structure

weather:
  api:
    key: a2489b6541ed95105459dce2faeb4d35